### ISSUE TITLE
Create and test TimeBlock

### ISSUE THREAD

**Issue by AndrewRoe34** [Sourceware-Lab/realquick#19]
Create and test type Timeblock:
```go
type TimeBlock struct {
	ID        uint            `gorm:"primarykey"` // identifier for timeblock
	Tag       *Tag            // label and color for timeblock
	Name      string          // name for timeblock
	Days      *string         // days of the week timeblock recurs
	Recur     bool            // whether timeblock recurs
	StartDate time.Time       // start date for timeblock
	EndDate   *time.Time      // end date for timeblock
	TimeStamp utils.TimeStamp // timestamp for timeblock
	Duration  time.Duration   // duration for a timestamp
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}
```
Notes for validation:

- If Recur is true, Days must hold a 7 digit string possessing only 1s and 0s representing the days of the week
- If Recur is false, Days must be nil or empty
- If Recur is false, StartDate and EndDate must share same date (they both must hold a value)
- If Recur is true, StartDate is required (represents when the recurring timeblock begins), but EndDate can be nil as that means to recur every week until the end of time lol
- TimeStamp (which is 2 time.Time) requires that they both hold the same date, but be at least 1 minute apart from each other (start being before end)

Here's how I implemented the TimeStamp validation originally:
```go
func newTimeStamp(start, end time.Time) (*timestamp, error) {
	if !start.After(end) || doDatesTimesMatch(start, end) {
		return nil, errors.New("timestamp requires that end time is after start")
	}
	return &timestamp{start, end}, nil
}

func doDatesTimesMatch(date1, date2 time.Time) bool {
	return doDatesMatch(date1, date2) && date1.Hour() == date2.Hour() && date1.Minute() == date2.Minute()
}
```

**Comment by peterHoburg** [comment]
#34
